### ISSUE TITLE
Would love a Readme

### ISSUE THREAD

**Issue by xmr-eric** [luigi1111/xmr.llcoins.net#1]
I just found your Github, and am excited to use your slowhash.html, sign.html, and addresstests.html files, but I don't really understand what they do :). I've been using the address generator and checktx tools for a while. They are great.

Anyway you can create a Readme for the cryptographic 2nd graders like myself?

**Comment by luigi1111** [comment]
Welcome. :) I just added it as a copy of the running site for people to see/have another way to download if they want, etc. I'll probably add something soon-ish.
