### ISSUE TITLE
Would love a GPG key and signature file of the addressgenerator page

### ISSUE THREAD

**Issue by xmr-eric** [luigi1111/xmr.llcoins.net#2]
Similar to the GPG key and .html.asc signature file of MoneroMooo at MoneroAddress.org. For cold storage on an offline liveUSB, it would be great to verify the download.

**Comment by luigi1111** [comment]
Good idea.

**Comment by Engelberg** [comment]
Consider setting up a profile on keybase and connecting it to your github profile as well as something else like your twitter account, so that there is some way to connect the signature to your identity.
