### ISSUE TITLE
Private view key not generating correctly

### ISSUE THREAD

**Issue by valiant1x** [luigi1111/xmr.llcoins.net#7]
When testing another CryptoNote based coin on addresstests.html, it would appear that the private view key is not generating correctly based upon a given seed (using button Gen 3&4). The CN coin in question has no revisions to the algorithm for address generation. Network byte is `fb01` (CryptoNoteConfig.h specifies `0xfb`, following the example for AEON we appended `01`). A standard 64 length simplewallet-compatible hexadecimal seed is used.

Seed/Private spend key: `B42F140750B202D89EFB367B666C6F12B2721C5CDF895AA0431BD5B6E71FF401`

Expected private view key: `A90432FBD1FE7636639E876C4A96ABDDAFAE6360D58292F5690D58A969BB9C0A`
Actual generated private view key: `b82659b12c9f36cb28a2f07613e6851ec740abf82952fabdba37f42930d9950e`

Public keys are generating properly.
Public view key: `025677374b0f05b75a6f8468d91bc53ab34b05611849e06d109b15ad72b68ac5`
Public spend key: `b00703d3a6723b4e4fae7bd2807baf02fde92d6a4744e2dea718298e9934bf68`

If the private view key is wrong, this also of course leads to the address being generated incorrectly after the first 46 characters:

Expected address: 
`iz5YdZVeyM3AvLoyuDiprWWGqHqY3kE6PewvQ2ihBKhmZ1t5oDSjv7Y1xTN3JFvjZkZzNXtu9nnmveYDPmJKJdAu2C74LLKRB`

Actual generated address (using incorrectly generated PVK):
`iz5YdZVeyM3AvLoyuDiprWWGqHqY3kE6PewvQ2ihBKhmZ1uentCDiP1E6E2r3adFJb3YLxXWszd8jKFxqFjBkoST2eFf3rWd1`

![wrongpvk](https://user-images.githubusercontent.com/29789261/31313937-461b5a76-abc0-11e7-9f9e-66ea0bad54c2.PNG)

**Comment by luigi1111** [comment]
https://github.com/valiant1x/intensecoin/blob/master/src/CryptoNoteCore/Account.cpp#L31

It looks to me like the view and spend keys are just random.

**Comment by valiant1x** [comment]
I had the same impression after I went through the wallet generating code and ended up at the same region you referenced. Unfortunately the code will have to be rewritten and any previously generated keys are non-restorable. Thanks for clearing this up.
